[package]
name = "hit-the-bumbum-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.0"
bevy_egui = "0.10"
bevy-inspector-egui = "0.7.4"
bevy_asset_ron = "0.3.0"
serde = "1.0.135"
